### ISSUE TITLE
Vias in Gerber don't match

### ISSUE THREAD

**Issue by MAG0101** [DL2DW/XoomFloppy-Pro_II#1]
Uploaded the gerber files to jlcpcb. Preview shows all vias at wrong position. 
Your Layout is made with Altium, so I have no chance to change it. Can you have a look at it please? ;)

**Comment by DL2DW** [comment]
I just uploaded the ZIP file again to JLCPCB. For me JLCPCB shows everything correctly. I had also ordered boards from JLCPCB with the ZIP file.

![image](https://user-images.githubusercontent.com/18718081/108485857-a6df0e00-729d-11eb-8f4e-70ae79dcc969.png)

![image](https://user-images.githubusercontent.com/18718081/108485965-d261f880-729d-11eb-8034-74ed6411dea1.png)

I had also uploaded the Gerber ZIP file to PCBWay. But there everything is also displayed correctly.

Can you test just download the repository from GitHub again and then test the ZIP file?

**Comment by DL2DW** [comment]
Thanks for the tip. I re-exported the Gerber files again, now JLCPCB shows it correctly again!

Interestingly, I always have boards made from the Gerber files themselves beforehand. And JLCPCB made these boards correctly without any problems. Apparently they had corrected the problem themselves. That's why I didn't notice it, because in the end everything was correct.

**Comment by MAG0101** [comment]
Hi Dirk,

thanks for the new file. Looks correct now after jlc import.

See the old one attached.

Greetings, Marcus
[image: Xoom1.png]

Am Fr., 19. Feb. 2021 um 10:49 Uhr schrieb Dirk Wouters <
notifications@github.com>:
